/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

drop schema if exists "proc" cascade;

CREATE SCHEMA "proc";{{ template "user_create_proc.sql".}} 
{{ template "user_update_proc.sql".}} 
{{ template "user_delete_proc.sql".}} 
{{ template "user_undo_delete_proc.sql".}} 
{{ template "incident_create_proc.sql".}} 
{{ template "incident_update_proc.sql".}} 
{{ template "incident_delete_proc.sql".}} 
{{ template "incident_undo_delete_proc.sql".}} 
{{ template "auditlog_create_proc.sql".}} 
{{ template "auditlog_update_proc.sql".}} 
{{ template "auditlog_delete_proc.sql".}} 
{{ template "auditlog_undo_delete_proc.sql".}} 
{{ template "service_create_proc.sql".}} 
{{ template "service_update_proc.sql".}} 
{{ template "service_delete_proc.sql".}} 
{{ template "service_undo_delete_proc.sql".}} 
{{ template "schemas_create_proc.sql".}} 
{{ template "schemas_update_proc.sql".}} 
{{ template "schemas_delete_proc.sql".}} 
{{ template "schemas_undo_delete_proc.sql".}} 
{{ template "serviceinstance_create_proc.sql".}} 
{{ template "serviceinstance_update_proc.sql".}} 
{{ template "serviceinstance_delete_proc.sql".}} 
{{ template "serviceinstance_undo_delete_proc.sql".}} 

